source "https://rubygems.org"

gem 'tshield', '0.5.2.0'

gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver', '= 2.53.0'
gem 'watir-webdriver', '= 0.9.1'
gem 'webdriver-user-agent', '= 7.4'
gem 'rake'
gem 'httparty'

